#!/bin/tcsh

setenv FREESURFER_HOME /Applications/freesurfer/
source $FREESURFER_HOME/SetUpFreeSurfer.csh

#Must set SUBJECTS_DIR to where data is or else uses what was set up when installing freesurfer (Should have the anatomical outputs from freesurfer under this subj_dir)
setenv SUBJECTS_DIR /path/2/subj_dir

#setenv to location where analysis is being run
setenv home /Volumes/DANIEL/

#setenv DICOMS /path/2/Diffusion/Dicoms

echo "-------------------------------------------------------------------------------------------------"

cd home
mkdir dti_freesurf
cd home/dti_freesurf
mkdir diffusion_recons
cd home

#list all subjects for the for loop inside ().
foreach subj ()

#list all condition
foreach cond (Ex)

echo "subj = " ${subj} ", cond = " ${cond}


mkdir /path/2/subj_dir/${subj}_${cond}
cd /path/2/subj_dir/${subj}_${cond}


cp DICOMS/*.dcm /path/2/subj_dir/${subj}_${cond}

#Convert into DCM (don't always need this step)
cd /path/2/subj_dir/${subj}_${cond}/
mri_convert image000001.dcm /path/2/subj_dir/${subj}_${cond}/dwi.nii.gz

#--sd subject ID path --s subject name (Created a new version of dt_recon because issue with registration - get on listserve conversation!)
dt_recon --sd /path/2/subj_dir --i /path/2/subj_dir/${subj}_${cond}/image000001.dcm --s ${subj}_${cond} --b dwi.bvals dwi.voxel_space.bvecs --o /Volumes/DANIEL/dti_freesurf/dtrecon/${subj}.${cond}.

end

end
