#!/bin/tcsh -f
#SBATCH --time=300:00:00
#SBATCH --mem=24000
#SBATCH --output=results
#SBATCH --cores=6

#Type this into the command line before submitting and to submit
#module load freesurfer
#module load matlab/2012b
#Type into command line
#foreach subj (AES101 AES102 AES104 AES107 AES108 AES109 AES110 AES111 AES113 AES114 AES115 AES116 AES117 AES118 AES119 AES120 AES121 AES122 AES123 AES124 AES126 AES127 AES129 AES130 AES133 AES134 AES136 AES137 AES138 AES139)
#foreach cond (Ex Rest)
#sbatch recon-all_bswift.sh ${subj} ${cond}
#end
#end



set echo
#input arguments from sbatch recon-all_bswift.sh ${subj} ${cond}
set subj= ($argv[1]) \
set cond= ($argv[2]) 


echo --------------------------------------
echo start reconall at:
echo working on ${subj}.${cond}
date
echo --------------------------------------

#create freesurfer directory
mkdir /homes/dcallow/freesurfer

#set the environment for recon-all processing and outputs
setenv SUBJECTS_DIR /homes/dcallow/freesurfer



recon-all -all -s ${cond}.${subj} -i /homes/dcallow/Dicoms/${subj}/session-${cond}/anat/image000001.dcm


