#!/bin/tcsh


setenv home /path/2/workstation

foreach subj (AES101 AES102 AES104 AES107 AES108 AES109 AES110 AES111 AES113 AES114 AES115 AES116 AES117 AES118 AES119 AES120 AES121 AES122 AES123 AES124 AES126 AES127 AES129 AES130 AES133 AES134 AES136 AES137 AES138 AES139)

foreach cond (Ex Rest)

mkdir tbss
cd ${home}/tbss/

echo "subj = " ${subj} ", cond = " ${cond}


cp /path/2/FA/fa-masked.nii.gz ${home}/tbss/${cond}.${subj}.nii.gz

end

end
echo "tbss pipeline ----------------------------------------------------------------------------------------------"

cd ${home}/tbss/

#Could change tbss_1_preproc source code comand to prevent from eroding ($FSLDIR/bin/fslmaths $f -min 1 -roi -ero 1 $X 1 $Y 1 $Z 0 1 FA/${f}_FA *remove -ero*)
tbss_1_preproc *.nii.gz

#Allign to fMRIB58_FA image (can change flag to -n if want to align to own best image)
tbss_2_reg -T


#mean derived from subject specific
tbss_3_postreg -S

#change input to threshold FA value of the skeleton
tbss_4_prestats 0.2
